[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
dirs = "4.0"
once_cell = "1.18"

[[bin]]
name = "server-rebuild"
path = "src/server_rebuild.rs"
