[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4.5.45", features = ["derive"] }
const_format = "0.2.34"
dirs = "6.0.0"
once_cell = "1.18"
