[package]
name = "mc_server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
dirs = "4.0"
git2 = "0.20.2"
once_cell = "1.18"
