[package]
name = "server"
version = "0.1.1"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
const_format = "0.2.34"
dirs = "6.0.0"
serde_json = "1.0.143"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
