[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.3"
proc-macro2 = "1.0.101"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
shellexpand = "3.1.1"

